### ISSUE TITLE
Mock server with OAuth support

### ISSUE THREAD

**Issue by kanadgupta** [bump-sh-examples/train-travel-api#25]
Hi there! This is a great example, thanks for putting it together.

I'd love if there was a mock server ([similar to how Petstore has one](https://petstore3.swagger.io/)) available to make actual requests against.

The Petstore server even has [a mock endpoint for an Implicit OAuth flow](https://petstore3.swagger.io/oauth/authorize), it'd be great if there was one for Train Travel and its Authorization Code-based OAuth flow ([Okta has a great playground that demonstrates this](https://petstore3.swagger.io/oauth/authorize)).

**Comment by philsturgeon** [comment]
@kanadgupta just wanted to let you know a plan is in progress here, but might take a little while to release.
