### ISSUE TITLE
Ideas for Improvements

### ISSUE THREAD

**Issue by philsturgeon** [bump-sh-examples/train-travel-api#3]
- [x] multiple content types (6f36875)
- [x] multiple examples
- [x] at least one webhook (f29099f)
- [x] Descriptions on tags (group description) with some markdown (16c5739)
- [ ] External docs on at least one tag ? (maybe on “Bookings”)
- [x] Polymorphism (anyOf)

**Comment by paulRbr** [comment]
>     * [x]  Descriptions on tags (group description) with some markdown ([16c5739](https://github.com/bump-sh-examples/train-travel-api/commit/16c573961aab9bca38b782a244992d51f3554b99))
> 
>     * [ ]  External docs on at least one tag ? (maybe on “Bookings”)

- About markdown on description tags, could you add a bit more text with some markdown (I'm thinking of maybe one [callout](https://docs.bump.sh/help/enhance-documentation-content/markdown-support/#information-call-outs), a link and some bold)
- Could you add an [external docs](https://spec.openapis.org/oas/v3.1.0#external-documentation-object) link inside a tag, and maybe also one at the root level of the document?

**Comment by philsturgeon** [comment]
@paulRbr I have been wondering what I could link to in externalDocs? I'd like to link to something that actually exists, but we don't have any relevant guides for the API or other source of documentation that is external to this. Do you have any ideas? The GitHub Repo?

**Comment by paulRbr** [comment]
A link to the github repo is good yes :+1:
